### ISSUE TITLE
Threat Investigation is not working 

### ISSUE THREAD

**Issue by FreeSpace911** [Open-Network-Insight/oni-demo#18]
Dear Admins, 

I just installed the docker demo and I have an issue with opening the Threat investigation based on the following error: 

`---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-9-11920f312ad6> in <module>()
     12 from IPython.display import display, Javascript, clear_output
     13 
---> 14 with open('/etc/duxbay.conf') as conf:
     15     for line in conf.readlines():
     16         if "DBNAME=" in line: DBNAME = line.split("=")[1].strip('\n').replace("'","");

IOError: [Errno 2] No such file or directory: '/etc/duxbay.conf'`

**Comment by Vikash082** [comment]
Do we have solution for this issue ?

**Comment by natedogs911** [comment]
Hello,

Threat investigation requires backend components in operation, such as a database to run queries.
the current docker demo does not have those components up but only the older version of spot ui.
That being said the whole demo is due for a refresh to bring it inline with the latest version and graphQL.

I have started on some of this work i just need to finalize the images.
